messages:
  playerNameMessage: "Player: %player_name%"
  playerLastJoinMessage: "Last Join: %player_last_join_date%"
  playerPositionMessage: "Position:"
  playerPositionMessageX: "X: %player_x%"
  playerPositionMessageY: "/ Y: %player_y%"
  playerPositionMessageZ: "/ Z: %player_z%"
  playerPositionMessageWorld: "| World: %player_world%"
  playerUUIDMessage: "UUID: %player_uuid%"